# Generated by Django 2.2.7 on 2019-12-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191202_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='Data de Nascimento',
        ),
    ]
