# Generated by Django 2.2.7 on 2019-12-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191202_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Data de Nascimento',
        ),
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
