# Generated by Django 2.2.7 on 2019-12-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('name', models.CharField(max_length=121)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='current_profile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_list',
            field=models.ManyToManyField(to='accounts.Movie'),
        ),
    ]
